sudo: required

env:
  - INSTALLATION=racket-x86
  - INSTALLATION=racket-x86-minimal
  # Temporarily disabled due to Typed Racket GUI test failures related to
  # extflonums and 32-bit builds, see racket/typed-racket#652
  # - INSTALLATION=racket-i386
  # - INSTALLATION=racket-i386-minimal
  - INSTALLATION=racket-x86-natipkg
  - INSTALLATION=racket-x86-natipkg-minimal

services:
  - docker

# See https://docs.travis-ci.com/user/docker/#Installing-a-newer-Docker-version
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install:
  - docker-compose build docker-compose
  - docker-compose build test-runner
  - docker-compose build ${INSTALLATION}

script:
  - docker-compose run test-runner ${INSTALLATION}
