version: "3.2"

# To build and test everything from scratch: "docker-compose up --build"
# But this runs all tests --- including the memory-hungry db tests --- in
# parallel, causing OOMEs and subsequent container death on typical laptops.

services:

  # TODO: This configuration is highly repetitive and should be made more
  # abstract. This is likely best achieved with a "test runner container" that
  # bind mounts the docker socket and calls the docker REST API from a script
  # to programmatically build and test each combination of installater options.
  # Doing this in Python would be relatively easy, since there's already an
  # official and supported docker client python library.

  # TODO: From-source builds aren't included yet, but they're not difficult to
  # add. Neither are minimal-with-prebuilt-pkgs installations, unix-style
  # installations, or tests for installation uninstall scripts. Doing this
  # after making the test runner container would be sensible.

  # TODO: Both installer downloads and package downloads could conceivably be
  # cached. Should wait until after test runner container is implemented.

  xvfb:
    build:
      context: .
      dockerfile: Dockerfile.xvfb
    # x11vnc requires a shared IPC namespace with the X server it proxies
    ipc: host
  x11vnc:
    build:
      context: .
      dockerfile: Dockerfile.x11vnc
    ipc: host
    environment:
      DISPLAY: xvfb:0.0
    depends_on:
      - xvfb
  websockify:
    # TODO: This image was chosen via a lazy google search and may break at any
    # time without warning.
    image: efrecon/websockify
    command: 50000 x11vnc:5900
    ports:
      - "50000:50000"
    depends_on:
      - x11vnc
  novnc:
    build:
      context: .
      dockerfile: Dockerfile.novnc
    volumes:
      - nginx-html:/usr/share/novnc
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./novnc-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      # The nocopy option is needed to ensure that novnc's preexisting files
      # are copied into the nginx-html volume, then copied from the nginx-html
      # volume into the nginx contaier itself. Without nocopy, nginx's files in
      # the /usr/share/nginx/html directory could get copied into the volume
      # instead of the other way around. Technically the read-only option and
      # the dependency on novnc (ensuring novnc uses the volume first) should
      # prevent that from happening, but that's a little too magic to rely on.
      - nginx-html:/usr/share/nginx/html:ro,nocopy
    depends_on:
      - novnc
      - websockify

  racket-x86:
    image: racket-x86
    build:
      context: .
      dockerfile: Dockerfile.installer
      # We use a YAML anchor for the build args to set a common version,
      # installer website, and installer path for building all installation
      # service images. See racket-x86-minimal.build.args for an example of how
      # the anchor is used.
      args: &default-build-args
        RACKET_VERSION: "${RACKET_VERSION}"
        RACKET_INSTALLER_HOST: "${RACKET_INSTALLER_HOST}"
        RACKET_INSTALLER_PATH_PREFIX: "${RACKET_INSTALLER_PATH_PREFIX}"
        RACKET_INSTALLER_PLATFORM: "${RACKET_PLATFORM_LINUX_64}"
        RACKET_INSTALLER_DIST: "${RACKET_DIST_FULL}"
    command: racket -e '(+ 1 2)'
  racket-x86-test:
    image: racket-x86-test
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        RACKET_IMAGE: racket-x86
  racket-x86-test-gui:
    build:
      context: .
      dockerfile: Dockerfile.test-gui
      args:
        RACKET_TEST_IMAGE: racket-x86-test
    environment:
      DISPLAY: xvfb:0.0
    depends_on:
      - xvfb

  racket-x86-minimal:
    image: racket-x86-minimal
    build:
      context: .
      dockerfile: Dockerfile.installer
      args:
        # We import the default build args and overwrite the desired platform
        # and distribution type. The platform defaults to x86_64 linux already
        # but the goal of default-build-args is just to set where installers are
        # downloaded, not specify a default platform and distribution.
        # Unfortunately, it's hard to include some keys and not others in an
        # anchor so we accept a little apparent redundancy.
        <<: *default-build-args
        RACKET_INSTALLER_PLATFORM: "${RACKET_PLATFORM_LINUX_64}"
        RACKET_INSTALLER_DIST: "${RACKET_DIST_MINIMAL}"
    command: racket -e '(+ 1 2)'
  racket-x86-minimal-test:
    image: racket-x86-minimal-test
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        RACKET_IMAGE: racket-x86-minimal
  racket-x86-minimal-test-gui:
    build:
      context: .
      dockerfile: Dockerfile.test-gui
      args:
        RACKET_TEST_IMAGE: racket-x86-minimal-test
    environment:
      DISPLAY: xvfb:0.0
    depends_on:
      - xvfb

  racket-i386:
    image: racket-i386
    build:
      context: .
      dockerfile: Dockerfile.installer
      args:
        <<: *default-build-args
        # Base images changed to i386 variants, as using the default images
        # won't compile due to architecture assumptions.
        RACKET_IMAGE_FOR_INSTALLER: i386/buildpack-deps
        RACKET_IMAGE_FOR_RUNTIME: i386/buildpack-deps
        RACKET_INSTALLER_PLATFORM: "${RACKET_PLATFORM_LINUX_32}"
        RACKET_INSTALLER_DIST: "${RACKET_DIST_FULL}"
    command: racket -e '(+ 1 2)'
  racket-i386-test:
    image: racket-i386-test
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        RACKET_IMAGE: racket-i386
  racket-i386-test-gui:
    build:
      context: .
      dockerfile: Dockerfile.test-gui
      args:
        RACKET_TEST_IMAGE: racket-i386-test
    environment:
      DISPLAY: xvfb:0.0
    depends_on:
      - xvfb

  racket-i386-minimal:
    image: racket-i386-minimal
    build:
      context: .
      dockerfile: Dockerfile.installer
      args:
        <<: *default-build-args
        RACKET_IMAGE_FOR_INSTALLER: i386/buildpack-deps
        RACKET_IMAGE_FOR_RUNTIME: i386/buildpack-deps
        RACKET_INSTALLER_PLATFORM: "${RACKET_PLATFORM_LINUX_32}"
        RACKET_INSTALLER_DIST: "${RACKET_DIST_MINIMAL}"
    command: racket -e '(+ 1 2)'
  racket-i386-minimal-test:
    image: racket-i386-minimal-test
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        RACKET_IMAGE: racket-i386-minimal
  racket-i386-minimal-test-gui:
    build:
      context: .
      dockerfile: Dockerfile.test-gui
      args:
        RACKET_TEST_IMAGE: racket-i386-minimal-test
    environment:
      DISPLAY: xvfb:0.0
    depends_on:
      - xvfb

  # TODO: Figure out why natipkg builds are failing. Seems to be related to
  # problems with the libssl and libcrypto (OpenSSL libs) libs included in the
  # racket-x86_64-linux-natipkg-2 package.

  racket-x86-natipkg:
    image: racket-x86-natipkg
    build:
      context: .
      dockerfile: Dockerfile.installer
      args:
        <<: *default-build-args
        RACKET_INSTALLER_PLATFORM: "${RACKET_PLATFORM_LINUX_NATIPKG_64}"
        RACKET_INSTALLER_DIST: "${RACKET_DIST_FULL}"
    command: racket -e '(+ 1 2)'
  racket-x86-natipkg-test:
    image: racket-x86-natipkg-test
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        RACKET_IMAGE: racket-x86-natipkg
  racket-x86-natipkg-test-gui:
    build:
      context: .
      dockerfile: Dockerfile.test-gui
      args:
        RACKET_TEST_IMAGE: racket-x86-natipkg-test
    environment:
      DISPLAY: xvfb:0.0
    depends_on:
      - xvfb

  racket-x86-natipkg-minimal:
    image: racket-x86-natipkg-minimal
    build:
      context: .
      dockerfile: Dockerfile.installer
      args:
        <<: *default-build-args
        RACKET_INSTALLER_PLATFORM: "${RACKET_PLATFORM_LINUX_NATIPKG_64}"
        RACKET_INSTALLER_DIST: "${RACKET_DIST_MINIMAL}"
    command: racket -e '(+ 1 2)'
  racket-x86-natipkg-minimal-test:
    image: racket-x86-natipkg-minimal-test
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        RACKET_IMAGE: racket-x86-natipkg-minimal
  racket-x86-natipkg-minimal-test-gui:
    build:
      context: .
      dockerfile: Dockerfile.test-gui
      args:
        RACKET_TEST_IMAGE: racket-x86-natipkg-minimal-test
    environment:
      DISPLAY: xvfb:0.0
    depends_on:
      - xvfb

volumes:
  nginx-html:
