version: "3.2"

services:
  test-base:
    image: test-base
    build:
      context: /etc/racket-test-runner
      dockerfile: Dockerfile.test
      args:
        RACKET_IMAGE: ${RACKET_IMAGE}
  test-nogui:
    image: test-base
    command: ["/bin/sh", "-c", "/usr/bin/racket-tests.sh"]
  test-gui:
    image: test-base
    command: ["/bin/sh", "-c", "/usr/bin/racket-gui-tests.sh"]
    environment:
      DISPLAY: ${RACKET_TESTS_X11_DISPLAY}

networks:
  default:
    external:
      name: ${RACKET_TESTS_X11_NETWORK}
