version: "3.2"

services:
  script-inplace:
    image: racket-${INSTALLER_TYPE}-script-inplace
    build: &default-build
      context: /etc/racket-installer
      dockerfile: Dockerfile.script-inplace
      args:
        RACKET_BASE_IMAGE: ${RACKET_BASE_IMAGE}
        INSTALLER_IMAGE: download-${INSTALLER_TYPE}
        INSTALLER_PATH: ${INSTALLER_PATH}
  script-unixstyle:
    image: racket-${INSTALLER_TYPE}-script-unixstyle
    build:
      <<: *default-build
      dockerfile: Dockerfile.script-unixstyle
